# print('Welcome to super simple calculator')
# a = float(input('enter your first number : '))
# b = float(input('input second number : '))
# print('your answer is', a * b)

print('Welcome to my calculator')
a = int(input('enter first number :'))
b = int(input('enter second number :'))
print('Addition', a + b)
print('Subtraction', a - b)
print('Multiplication', a * b)
print('Division', a / b)
print('Exponentiation' , a ** b)
print('Modulus', a % b)